apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"mlmodel-service","namespace":"default"},"spec":{"ports":[{"port":80,"protocol":"TCP","targetPort":8080}],"selector":{"app":"mlmodel"},"type":"NodePort"}}
  creationTimestamp: "2020-08-25T21:17:53Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
      f:spec:
        f:externalTrafficPolicy: {}
        f:ports:
          .: {}
          k:{"port":80,"protocol":"TCP"}:
            .: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:app: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: kubectl
    operation: Update
    time: "2020-08-25T21:17:53Z"
  name: mlmodel-service
  namespace: default
  resourceVersion: "424514"
  selfLink: /api/v1/namespaces/default/services/mlmodel-service
  uid: a157078d-513b-4585-9052-165c5bee7a43
spec:
  clusterIP: 10.106.37.34
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31389
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: mlmodel
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
