apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlmodel-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlmodel
  template:
    metadata:
      labels:
        app: mlmodel
    spec:
      containers:
      - name: mlmodel-docker
        image: wilbrodchipomho/postgrad-msc:200
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
